version: "3.9"

services:
  gateway-service:
    image: nginx:1.27-alpine
    container_name: flowsight-gateway-service
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ingestion-service
    networks:
      - flowsight-net

  ingestion-service:
    build:
      context: ../ingestion-service
    container_name: flowsight-ingestion-service
    environment:
      - INGESTION_DB_URL=postgresql+asyncpg://flowsight:flowsight@postgres:5432/flowsight
      - INGESTION_DB_SCHEMA=ingestion
      - INGESTION_REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    networks:
      - flowsight-net

  postgres:
    image: postgres:16-alpine
    container_name: flowsight-postgres
    environment:
      - POSTGRES_USER=flowsight
      - POSTGRES_PASSWORD=flowsight
      - POSTGRES_DB=flowsight
    ports:
      - "5432:5432"
    networks:
      - flowsight-net

  redis:
    image: redis:7-alpine
    container_name: flowsight-redis
    ports:
      - "6379:6379"
    networks:
      - flowsight-net

networks:
  flowsight-net:
    driver: bridge
